### ISSUE TITLE
Connection failure under Windows

### ISSUE THREAD

**Issue by solatis** [fpco/stackage-install#1]
I get a connection failure when trying to use stackage-install:

```
C:\Users\leon\Documents\GitHub> stackage-install stackage-upload
Downloading stackage-upload-0.1.0.3
stackage-install.exe: FailedConnectionException "s3.amazonaws.com" 443
C:\Users\leon\Documents\GitHub>
```

I suspect this is a certificate error ?

**Comment by snoyberg** [comment]
No, that's a timeout error. I could bump the timeout value to help with that, but can you try running it again and see if it changes?

**Comment by solatis** [comment]
The problem repeats itself inifnitely, while I have no problems connecting to the site when using a web browser. I cannot find any "withSocketsDo" in this repo, but I suppose that command is in some other library?

**Comment by snoyberg** [comment]
Yes, http-client calls `withSocketsDo` for us. I'll add a longer timeout now, and then ask you to check again.

**Comment by solatis** [comment]
My internet is pretty bad (located in Cambodia at the moment), so that might be the reason.

**Comment by snoyberg** [comment]
Is it taking about 30 seconds to give you that error message?

**Comment by solatis** [comment]
No, +- 3 seconds.

**Comment by snoyberg** [comment]
Oh, that's unexpected. I just pushed a commit that extends the timeout, can you try it?

**Comment by solatis** [comment]
I think you broke the build. :) 

It's getting late here, I've made a fork and will take a look at this tomorrow morning.

**Comment by snoyberg** [comment]
I already pushed a commit that fixes it actually.

**Comment by solatis** [comment]
Confirmed, thanks!
