### ISSUE TITLE
--keep-going

### ISSUE THREAD

**Issue by gitfoxi** [fpco/stackage-install#5]
Is there an option to try and build as much as possible in the face of failing builds?

**Comment by snoyberg** [comment]
This package has been superseded by [Stack](http://haskellstack.com/), I'd recommend using that instead.

**Comment by gitfoxi** [comment]
Thanks. I'm using stack but didn't understand the repos. I ask on the mailing list. Is this the right one? https://groups.google.com/forum/#!forum/stackage

**Comment by snoyberg** [comment]
No, please check out the list of resources on the Stack homepage:
http://docs.haskellstack.org/en/stable/README.html#questions-feedback-discussion

**Comment by gitfoxi** [comment]
Thank you.
