### ISSUE TITLE
Inaccurate version bounds in  .cabal file

### ISSUE THREAD

**Issue by hvr** [fpco/stackage-install#6]
`stackage-install-0.1.1.1` says it needs `http-client >= 0.4`. But with http-client-0.5.0, you run into

```
Preprocessing library stackage-install-0.1.1.1...
[1 of 1] Compiling Stackage.Install ( Stackage/Install.hs, /tmp/stackage-install-0.1.1.1/dist-newstyle/build/stackage-install-0.1.1.1/build/Stackage/Install.o )

Stackage/Install.hs:46:61-71: error:
    Module ‘Network.HTTP.Client’ does not export ‘checkStatus’
```

Turns out, `checkStatus` was removed in `http-client-0.5`. In other words, an upper bound `< 0.5` is missing here.

(This problem was already mentioned [here](https://github.com/fpco/stackage-curator/issues/22#issuecomment-233118149) but is being filed here where it actually belongs, and so it doesn't get forgotten)

**Comment by snoyberg** [comment]
New version released.

**Comment by hvr** [comment]
Btw, you forgot to retrofit upper bounds in affected previous releases; I took care of it to properly resolve this bug:
- https://hackage.haskell.org/package/stackage-install-0.1.1.1/revisions/
- https://hackage.haskell.org/package/stackage-install-0.1.1.0/revisions/
- https://hackage.haskell.org/package/stackage-install-0.1.0.3/revisions/
- https://hackage.haskell.org/package/stackage-install-0.1.0.2/revisions/

Now http://matrix.hackage.haskell.org/package/stackage-install is all green again
